version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  reviewers:
  - nwtgck
  assignees:
  - nwtgck
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">= 11.a, < 12"
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a, < 14"
  - dependency-name: "@types/node"
    versions:
    - ">= 14.a, < 15"
  - dependency-name: "@types/node"
    versions:
    - 12.19.16
    - 12.20.10
    - 12.20.2
    - 12.20.3
    - 12.20.5
    - 12.20.7
    - 12.20.8
    - 15.0.0
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.5
    - 3.6.8
    - 3.6.9
  - dependency-name: karma
    versions:
    - 6.1.1
    - 6.1.2
    - 6.2.0
    - 6.3.0
    - 6.3.1
  - dependency-name: jasmine-core
    versions:
    - 3.7.0
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.2.2
  - dependency-name: karma-typescript
    versions:
    - 5.3.0
